// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems//ClimberRung.h"
#include "subsystems/DriveMovement.h"
#include "subsystems/IndexerBall.h"
#include "subsystems/IntakeBall.h"
#include "subsystems/LimelightVision.h"
#include "subsystems/ShooterBall.h"

#include "commands/LimelightVision/AimbotSequential.h"
#include "commands/AutonomousCommand.h"
#include "commands/IndexerBall/Backward.h"
#include "commands/ClimberRung/Climb.h"
#include "commands/IntakeBall/DownYesRoll.h"
#include "commands/ShooterBall/BallPistonBall/ExtendRetract.h"
#include "commands/DriveMovement/FlipDrive.h"
#include "commands/IndexerBall/Forward.h"
#include "commands/LimelightVision/SetShootSpeed.h"
#include "commands/ShooterBall/ShootSequential.h"
#include "commands/ShooterBall/StartFlywheel.h"
#include "commands/ShooterBall/StopFlywheel.h"
#include "commands/ShooterBall/StopIndexer.h"
#include "commands/DriveMovement/SwerveDrive.h"
#include "commands/IntakeBall/UpNoRoll.h"
#include "commands/LimelightVision/YawToTarget.h"
#include <frc/Joystick.h>
#include <frc/XboxController.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
// The robot's subsystems
DriveMovement m_driveMovement;
IntakeBall m_intakeBall;
IndexerBall m_indexerBall;
ShooterBall m_shooterBall;
ClimberRung m_climberRung;
LimelightVision m_limelightVision;


frc::Joystick* getXboxController2();
frc::XboxController* getXboxController1();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

private:

    RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// Joysticks
frc::Joystick m_xboxController2{2};
frc::XboxController m_xboxController1{1};

frc::SendableChooser<frc2::Command*> m_chooser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

AutonomousCommand m_autonomousCommand;
    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};