# Builds and tests robot code on pull requests to the main branch
name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the WPILib docker container
    # https://hub.docker.com/r/wpilib/roborio-cross-ubuntu/tags
    container: wpilib/roborio-cross-ubuntu:2022-20.04

    steps:
    - uses: actions/checkout@v2

    # Some libraries don't support building for desktop on Linux and it makes the build take much longer
    - name: Locally disable building desktop version
      run: sed -i "s/def includeDesktopSupport = true/def includeDesktopSupport = false/" "${GITHUB_WORKSPACE}/build.gradle"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build robot code
      run: ./gradlew build
